### ISSUE TITLE
Actividad 1

### ISSUE THREAD

**Issue by Lussssia** [Lussssia/Aplicaciones_TCP_IP#1]
Actividad 1: Obtener información del sistema en formato JSON utilizando un script Bash
Historia de usuario:

Como usuario de Ubuntu, quiero ejecutar un script Bash que me permita obtener información del sistema en formato JSON. Esto me brindará una forma conveniente de recopilar los detalles del sistema, como el sistema operativo, el kernel, la CPU, la memoria total, el espacio en disco, la versión de Bash y la versión de Python.
Criterios de aceptación:

    Como usuario de Ubuntu, quiero poder ejecutar el script Bash desde la línea de comandos en mi sistema.
    El script debe recopilar automáticamente la información del sistema requerida, siguientes claves y valores (estos son de ejemplo):
        "sistema_operativo": "Ubuntu 20.04"
        "kernel": "5.4.0-86-generic"
        "cpu": "Intel Core i7-8700K"
        "memoria_total": "16 GB"
        "espacio_disco": "500 GB"
        "version_bash": "5.0.17"
        "version_python": "3.8.10" (por ejemplo, si la versión de Python instalada es 3.8.10)
    El script debe imprimir el objeto JSON resultante en la salida estándar.
    El script debe guardar la salida como objeto JSON, con el nombre de archivo sistem_info.json

Definición de terminado:

    Se ha creado un script Bash llamado "system_info.sh" que cumple con los criterios de aceptación.
    El script ha sido probado con éxito en Ubuntu y produce un objeto JSON con la información del sistema requerida.
    El objeto JSON impreso en la salida estándar coincide con las claves y valores especificados anteriormente.
    Se ha documentado claramente cómo ejecutar y probar el script en el repositorio designado, incluyendo cualquier dependencia o configuración adicional que pueda ser necesaria.
    versionado en github en el repositorio original

Resultado esperado:

    script en el repositorio original
    archivo con la informacion del sistema del usuario sistem_info.json en el repositorio original

**Comment by LucaPollano2000** [comment]
Revisado.
